### ISSUE TITLE
Collision detection allows cutting corners...

### ISSUE THREAD

**Issue by mikelehen** [mckoss/racetrack#16]
With #15, if I use my racer on the BIG_OVAL track, it's able to cut the corners:

![image](https://user-images.githubusercontent.com/206364/224224441-c45fc47b-30a6-4aa8-9bdd-222ca270c62d.png)

I'm assuming that it's calculating the intermediate points and they round to points that are on the edge of the track, so it allows it.  But I think it probably shouldn't, since technically it's cutting inside the corner of the track?

I'm guessing you may have a clear idea of how to fix this, since you wrote the collision detection, but I can dig into it if you want...

**Comment by mckoss** [comment]
The reason being that on the grid-scale, the only points traversed are considered "on the track".

A couple of work arounds come to mind.

1. Increase the grid resolution (smaller ```track.grid``` values)
2. Be sure to define tracks where the boundary of the track lies *between* grid points.  It may still "cut the corner" - but will be less egregious.
3. Disallow lines where even adjacent grids out of bounds are considered a crash:
![image](https://user-images.githubusercontent.com/82750/224456147-16a7e94d-8c43-4a6b-bd18-095752154798.png)

All but the last is no code change - and the code change may have unintended consequences?

**Comment by mikelehen** [comment]
Oh, yeah.  For some reason I was thinking it'd be desirable to have the track boundaries lie on the grid points, but you're right.  Putting the boundary between grid points makes sense.  #20 fixes BIG_OVAL.  I think that's probably good enough for now at least.
